DECLARE
  PER_ID NUMBER;
BEGIN


  UPDATE PRIOR_CALC
     SET JOB_NAME   = NULL,
         SESSION_ID = NULL,
         PRIOR_NUM  = NULL,
         STREAM_NUM = NULL,
         IS_FON     = 1;



  UPDATE RGLOBAL
     SET RGLOBAL_STRING = TO_CHAR(SYSDATE, 'DD'),
         RGLOBAL_NUMBER = TO_NUMBER(TO_CHAR(SYSDATE, 'DD'))
   WHERE RGLOBAL_ID = 71;

  COMMIT;

  DBMS_SCHEDULER.RUN_JOB('JOB_FOR_STREAMS', FALSE);

END;
