SELECT ROWNUM, tt.*
	FROM (SELECT DISTINCT S.OWNER, S.NAME, U.USER_PARENT
				 FROM DBA_SOURCE S, USERS U
				WHERE UPPER(TEXT) LIKE '%PSP_MAIL%'
					AND S.OWNER <> 'SYS'
					AND U.USER_NAME = S.OWNER
				ORDER BY 2, 3) tt
