select *
from   DBA_EXTENTS E
where  E.FILE_ID = DBMS_UTILITY.DATA_BLOCK_ADDRESS_FILE(8792761)
       and
       DBMS_UTILITY.DATA_BLOCK_ADDRESS_BLOCK(8792761) between E.BLOCK_ID and
       E.BLOCK_ID + E.BLOCKS - 1